class Config:
    DEFAULT_FILE_CONFLICT_BEHAVIOR = 'skip'  # Global default


# Constants
SSIM_BETA = 4.0
SSIM_THRESHOLD = 0.2
SUPERPIXEL_SEGMENTS = 2000
SUPERPIXEL_COMPACTNESS = 5
SUPERPIXEL_CHANGE_THRESHOLD = 0.01
SUPERPIXEL_TIMEOUT = 30

# Folder paths
SCREENSHOTS_FOLDER = "screenshots/originals"
DIFFS_FOLDER = "screenshots/diffs"
RECREATIONS_FOLDER = "screenshots/recreations"
